### ISSUE TITLE
A suggestion or a personal request

### ISSUE THREAD

**Issue by GigioFu** [Cyrillya/Autofish#2]
Hi Crapsky233, my name is Geovane and I'm from Brazil, so if my English is bad, I'm sorry.

I played Terraria with your mod and LuiAFK and noticed that LuiAFK's unlimited fishing rods don't work with Autofish.

Can you make them be compatible, plz? Or just tell me what I need to do to make them work.

Thank you 😊.

**Comment by Cyrillya** [comment]
LuiAFK's unlimited fishing rods use a different way for fishing besides vanilla. I have no idea how to do that. So you may have to use vanilla fishing rods. Sorry but I will not make them be compatible.
