### ISSUE TITLE
Reporting bugs in mods for Ver 1.3

### ISSUE THREAD

**Issue by Chitosen** [Cyrillya/Autofish#4]
First, I apologize that I am not a very good English speaker and that my writing is difficult to read.

I have confirmed that since this mod has been Ver 0.2.5, there is a problem with the bobber being thrown back the moment an item other than Vanilla (added by another mod) is hooked up.

Simply put, it is now impossible to fish for items added by the mod.

I am reporting this as a bug because I was able to catch fish with no problem in previous versions.

Any other information I can provide would be appreciated.

**Comment by Cyrillya** [comment]
When I use this mod with Calamity Mod it seems to work fine. Can you tell me what mod is this problem happening on? It would be better to provide a tmod file.

**Comment by Chitosen** [comment]
I was also using it with the Calamity mod and had this bug.

I then disabled all other mods, deleted and re-downloaded the tMOD and all data related to it, and tried it in minimal configuration(autofish,Calamity,Cheat Sheet) with no improvement.

I forgot to report earlier that if I use a fishing rod with multiple lines, I can fish additional MOD items only if I hang them at the same time as vanilla items.
(Therefore, it is impossible to catch anything in an environment where only additional items are available, such as the lava in the Brimstone crag biome.)

Video of lava fishing at Brimstone Crag
https://youtu.be/k9y5KfBimu0

**Comment by Cyrillya** [comment]
Just updated to v0.2.7, the bug should be fixed with the newest version.
https://youtu.be/K7py8RAbE1E
Thanks for reporting!
