### ISSUE TITLE
【建议】兼容灾厄宝匣

### ISSUE THREAD

**Issue by Phoupraw** [Cyrillya/Autofish#7]
在我在硫磺海挂机钓鱼了几个小时之后我才发现，如果只启用“自动钓宝匣”，那么灾厄的宝匣是不会被钓起的。

我觉得有三个办法可以避免其他人重蹈我的覆辙：
1. 在创意工坊或模组简介说明玩家需要手动把灾厄的宝匣加进“其它自动捕获物品”。
2. 模组自己自动把灾厄的宝匣加进“其它自动捕获物品”。
3. “自动钓宝匣”兼容灾厄的宝匣。

灾厄有四种宝匣：深渊匣、沉沦匣、硫磺火匣、星幻匣。

**Comment by Cyrillya** [comment]
有一个方法可以完美解决——告诉灾厄作者之一让他们修复这个Bug（产生原因是因为他们没有给宝匣设置`ItemID.Sets.IsCrate[Type]=true`
我几周前就已经报告并修复了，接下来就是灾厄更不更新的问题，稍微等等
